# Generated by Django 5.1.4 on 2025-08-28 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='ddata/agents/')),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'lead',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe the maintenance issue')),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('preferred_date', models.DateField(blank=True, help_text='Preferred maintenance date', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'maintenance_request',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10, verbose_name='Listing Type')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(blank=True, default=True, null=True)),
                ('list_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_hot_selling', models.BooleanField(blank=True, default=False, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='ddata/properties/%Y/%m/%d/')),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('building_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maintenance_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('builtup_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('facing_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('garden_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_availability', models.CharField(blank=True, max_length=20, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=20, null=True)),
                ('commercial_type', models.CharField(blank=True, max_length=20, null=True)),
                ('floor_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('loading_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parking_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('office_type', models.CharField(blank=True, max_length=20, null=True)),
                ('furnishing_type', models.CharField(blank=True, max_length=20, null=True)),
                ('conference_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('reception_area', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('units_in_complex', models.PositiveIntegerField(blank=True, null=True)),
                ('corner_unit', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('end_unit', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('hoa_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('INDEPENDENT_HOUSE', 'Independent House'), ('PLOT', 'Plot / Land'), ('COMMERCIAL', 'Commercial Property'), ('STUDIO', 'Studio Apartment')], help_text='Select the type of property, e.g., House, Villa, Plot/Land, Apartment', max_length=100)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'property_type',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ddata/property_images/%Y/%m/%d/')),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='squarebox.property')),
            ],
            options={
                'db_table': 'property_image',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squarebox.propertytype'),
        ),
    ]
