# Generated by Django 5.1.4 on 2026-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
