# Generated by Django 5.1.4 on 2026-02-06 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mck_auth', '0001_initial'),
        ('mck_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttyperolepermission',
            name='master_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mck_master.masterpermission'),
        ),
        migrations.AddField(
            model_name='accounttyperolepermission',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mck_auth.account'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mck_auth.accounttyperole'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
