# Generated by Django 5.1.4 on 2026-02-06 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ddata')),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ddata')),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ddata')),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'client_feedback',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('iso_4217_alpha', models.CharField(max_length=200)),
                ('iso_4217_numeric', models.CharField(max_length=200)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('capital_city', models.CharField(max_length=200)),
                ('telephone_calling_code', models.CharField(max_length=5)),
                ('internet_domain_code', models.CharField(max_length=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ddata')),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='MasterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('class_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('module_name', models.CharField(max_length=255)),
                ('function_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'master_permission',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ddata')),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='SupportPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_key', models.CharField(max_length=255)),
                ('support_value', models.CharField(max_length=255)),
                ('support_description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=1)),
            ],
            options={
                'db_table': 'support_page_content',
            },
        ),
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('CUS_IOS_APP', 'IOS App'), ('CUS_ANDROID_APP', 'Android App')], default='CUS_ANDROID_APP', max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('released_on', models.DateTimeField(auto_now_add=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=5)),
            ],
            options={
                'db_table': 'version_control',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('location', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='mck_master.country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='mck_master.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ddata')),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mck_master.category')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
    ]
