# Generated by Django 5.1.4 on 2026-01-31 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mck_master', '0003_profile_created_by_profile_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_by',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
