# Generated by Django 5.1.4 on 2026-01-13 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mck_master', '0003_profile_created_by_profile_created_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.AlterField(
        model_name='profile',
        name='created_by',
        field=models.CharField(max_length=8),
    ),
    migrations.AlterField(
        model_name='profile',
        name='created_on',
        field=models.DateTimeField(auto_now_add=True),
    ),
    migrations.AlterField(
        model_name='profile',
        name='updated_by',
        field=models.CharField(max_length=8),
    ),
    migrations.AlterField(
        model_name='profile',
        name='user',
        field=models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='profile',
            to=settings.AUTH_USER_MODEL,
        ),
    ),
]

